camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: admin
  filter:
    create: All tasks

test:
  frodborrower: false
  froddocs: false
  frodobject: false
  frodowner: false
  bankdecision: true
  clientdecision: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driverClassName: org.postgresql.Driver

camunda:
  bpm:
    database:
      type: postgres
      schema-update:  true
    jpa:
      enabled: true
server:
  port: 8083
