
create table Applicant(
                          id SERIAL primary key,
                          app_date date,
                          client_id int,
                          amount float,
                          corrid int,
                          seller_id int,
                          frod_buyer bool,
                          frod_docs bool,
                          frod_object bool,
                          frod_app bool,
                          docs_id int,
                          object_id int,
                          address varchar(255),
                          type_of_object varchar(255),
                          date_applicant date,
                          date_signing date,
                          bank_name varchar(255),
                          code_client varchar(255),
                          decision varchar(255),
                          f_name varchar(255),
                          s_name varchar(255),
                          o_name varchar(255),
                          sex varchar(255),
                          date_birth varchar(255),
                          phone varchar(255),
                          email varchar(255),
                          civil varchar(255),
                          snils varchar(255),
                          inn varchar(255),
                          n_pass varchar(255),
                          s_pass varchar(255),
                          type_seller varchar(255),
                          add_date varchar(255),
                          d_applicant bytea,
                          d_vipiska_iz_domovoi bytea,
                          d_kadastr_pass bytea,
                          d_tech_pass bytea,
                          d_owner_order bytea,
                          d_price_order bytea,
                          d_ndfl bytea,
                          d_work bytea
);